# Generated by Django 4.1.4 on 2023-12-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('about_you', models.TextField()),
                ('education', models.TextField()),
                ('career', models.TextField()),
                ('job_1_start', models.CharField(blank=True, max_length=10, null=True)),
                ('job_1_end', models.CharField(blank=True, max_length=10, null=True)),
                ('job_1_details', models.TextField(blank=True, null=True)),
                ('job_2_start', models.CharField(blank=True, max_length=10, null=True)),
                ('job_2_end', models.CharField(blank=True, max_length=10, null=True)),
                ('job_2_details', models.TextField(blank=True, null=True)),
                ('job_3_start', models.CharField(blank=True, max_length=10, null=True)),
                ('job_3_end', models.CharField(blank=True, max_length=10, null=True)),
                ('job_3_details', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.userprofile')),
            ],
        ),
    ]
